name: Test
'on':
  push: null
  pull_request: null
jobs:
  full:
    name: Node.js 17 Full
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm --frozen-lockfile install
      - name: Run tests
        run: make check
        env:
          NODE_OPTIONS: --openssl-legacy-provider
          FORCE_COLOR: 2
  short:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16
    name: Node.js ${{ matrix.node-version }} Quick
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm --frozen-lockfile install

      - name: Run unit tests
        run: make test
        env:
          FORCE_COLOR: 2
