name: Test
'on':
  push: null
  pull_request: null
jobs:
  full:
    name: Node.js 20 Full
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Run tests
        run: make check
        env:
          NODE_OPTIONS: --openssl-legacy-provider
          FORCE_COLOR: 2
  short:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18
          - 16
    name: Node.js ${{ matrix.node-version }} Quick
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Run unit tests
        run: make test
        env:
          FORCE_COLOR: 2
